#!/usr/bin/env bash
#
# setup-userspace-toolchain.sh — Acquire a musl-libc ARM toolchain for
#                                 building test_app userspace utilities
#                                 (hgpriv, hgicf, hgota, libnetat, libnetat_cli)
#
# The userspace tools must link against musl libc to run on OpenIPC targets,
# which use a musl-based rootfs.  The kernel module builds (build-matrix-local.sh)
# use a separate glibc-based cross-compiler from apt and are not affected.
#
# Two acquisition modes:
#
#   --buildroot <path>   Use the toolchain already built by an OpenIPC buildroot.
#                        <path> is the buildroot OUTPUT directory, e.g.
#                        ~/openipc/openipc-firmware/output
#                        This is the canonical option if you already have a
#                        firmware build; it gives exactly the toolchain the
#                        camera rootfs was linked against.
#
#   --download           Download the musl.cc arm-linux-musleabi-cross toolchain
#                        (lightweight alternative; no full buildroot needed;
#                        soft-float ARM + musl libc; matches the ABI of existing
#                        bin/arm-openipc-linux-musleabi-gcc/ binaries).
#
# After setup, add the toolchain to your PATH and build:
#
#   source toolchains/env.sh
#   make -C tools/test_app CC=arm-openipc-linux-musleabi-gcc
#
# Usage:
#   ./scripts/setup-userspace-toolchain.sh --buildroot ~/openipc/openipc-firmware/output
#   ./scripts/setup-userspace-toolchain.sh --download
#   ./scripts/setup-userspace-toolchain.sh --list
#   ./scripts/setup-userspace-toolchain.sh --help
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRIVER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TOOLCHAIN_DIR="$DRIVER_DIR/toolchains"

# musl.cc toolchain for soft-float ARM (matches OpenIPC musleabi ABI)
MUSL_CC_URL="https://musl.cc/arm-linux-musleabi-cross.tgz"
MUSL_CC_ARCHIVE_NAME="arm-linux-musleabi-cross.tgz"
MUSL_CC_UNPACK_DIR="arm-linux-musleabi-cross"
MUSL_CC_BIN_PREFIX="arm-linux-musleabi-"

# The canonical CC name used in GNUmakefile's BIN_SUBDIR.
# Symlinked from the musl.cc prefix so bin output matches existing pre-built
# binaries in bin/arm-openipc-linux-musleabi-gcc/.
OPENIPC_GCC_NAME="arm-openipc-linux-musleabi-gcc"

# ─── Helpers ─────────────────────────────────────────────────────────────────

usage() {
    cat <<USAGE
Usage: $0 <mode> [options]

Modes:
  --buildroot <output-dir>   Use toolchain from an existing OpenIPC buildroot output.
                              <output-dir> is the 'output/' directory of the buildroot,
                              e.g. ~/openipc/openipc-firmware/output
                              Canonical option if you already have a firmware build.

  --download                 Download musl.cc arm-linux-musleabi toolchain.
                              Lightweight alternative (~50 MB); no buildroot needed.
                              Matches ABI of existing bin/arm-openipc-linux-musleabi-gcc/
                              binaries (soft-float ARM, musl libc).

  --list                     List toolchains already set up under toolchains/.

  --help                     Show this help.

After setup:
  source toolchains/env.sh
  make -C tools/test_app CC=arm-openipc-linux-musleabi-gcc

USAGE
}

write_env_sh() {
    local bin_path="$1"
    local env_file="$TOOLCHAIN_DIR/env.sh"
    cat > "$env_file" <<EOF
# Source this file to activate the userspace toolchain for test_app builds.
# Generated by setup-userspace-toolchain.sh — do not edit manually.
#
#   source toolchains/env.sh
#   make -C tools/test_app CC=arm-openipc-linux-musleabi-gcc
#
export PATH="${bin_path}:\$PATH"
EOF
    echo "  Wrote: $env_file"
}

print_next_steps() {
    cat <<NEXT

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Next steps
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  1. Activate the toolchain:
       source toolchains/env.sh

     (Or add the bin path to your ~/.bashrc for persistent access.)

  2. Build all userspace tools:
       make -C tools/test_app CC=arm-openipc-linux-musleabi-gcc

  3. Binaries will be in:
       tools/test_app/bin/arm-openipc-linux-musleabi-gcc/

  4. Deploy to camera (example):
       scp tools/test_app/bin/arm-openipc-linux-musleabi-gcc/hgpriv root@<camera_ip>:/usr/bin/
       scp tools/test_app/bin/arm-openipc-linux-musleabi-gcc/hgicf  root@<camera_ip>:/usr/bin/
       scp tools/test_app/bin/arm-openipc-linux-musleabi-gcc/libnetat_cli root@<camera_ip>:/usr/local/bin/libnetat

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NEXT
}

list_toolchains() {
    if [[ ! -d "$TOOLCHAIN_DIR" ]]; then
        echo "No toolchains set up yet. Run this script to acquire one."
        return
    fi
    echo "Toolchains in: $TOOLCHAIN_DIR/"
    echo ""
    for d in "$TOOLCHAIN_DIR"/*/; do
        [[ -d "$d" ]] || continue
        local name
        name="$(basename "$d")"
        local gcc_path="$d/bin/arm-openipc-linux-musleabi-gcc"
        local status="missing gcc"
        if [[ -x "$gcc_path" ]]; then
            local ver
            ver=$("$gcc_path" --version 2>/dev/null | head -1 || echo "unknown")
            status="$ver"
        fi
        printf "  %-36s  %s\n" "$name" "$status"
    done
    if [[ -f "$TOOLCHAIN_DIR/env.sh" ]]; then
        echo ""
        echo "  Activate with: source toolchains/env.sh"
    fi
}

# ─── Mode: --buildroot ────────────────────────────────────────────────────────

setup_from_buildroot() {
    local br_output="$1"

    if [[ ! -d "$br_output" ]]; then
        echo "Error: buildroot output directory not found: $br_output"
        exit 1
    fi

    local br_bin="$br_output/host/bin"
    if [[ ! -d "$br_bin" ]]; then
        echo "Error: $br_bin does not exist."
        echo "       Is this a built buildroot output directory?"
        echo "       Expected layout: <output>/host/bin/<toolchain-prefix>gcc"
        exit 1
    fi

    # Find the gcc binary: prefer musleabi, accept gnueabi/gnueabihf variants
    local found_gcc=""
    for pattern in \
        "$br_bin/arm-openipc-linux-musleabi-gcc" \
        "$br_bin/arm-openipc-linux-gnueabi-gcc" \
        "$br_bin/arm-openipc-linux-gnueabihf-gcc"
    do
        if [[ -x "$pattern" ]]; then
            found_gcc="$pattern"
            break
        fi
    done

    if [[ -z "$found_gcc" ]]; then
        echo "Error: no arm-openipc-linux-*-gcc found in $br_bin"
        echo "       Available compilers:"
        ls "$br_bin"/arm-*-gcc 2>/dev/null | sed 's/^/         /' || echo "         (none)"
        exit 1
    fi

    local gcc_prefix
    gcc_prefix="$(basename "$found_gcc" | sed 's/gcc$//')"
    echo "━━━ Found buildroot toolchain: ${gcc_prefix}gcc"
    echo "    $found_gcc"
    echo "    $("$found_gcc" --version | head -1)"

    # Check ABI match
    if [[ "$found_gcc" != *musleabi* ]]; then
        echo ""
        echo "  WARNING: This buildroot was built with a glibc/gnueabi toolchain"
        echo "  ($found_gcc)."
        echo "  Binaries produced will link against glibc, not musl libc."
        echo "  They will run on cameras if glibc is present, but most OpenIPC"
        echo "  targets use musl libc.  Consider using --download instead for"
        echo "  a musleabi toolchain, or rebuilding the firmware with musl."
        echo ""
    fi

    mkdir -p "$TOOLCHAIN_DIR"

    # Create a stable symlink dir so env.sh has a consistent path
    local link_dir="$TOOLCHAIN_DIR/buildroot-openipc"
    rm -f "$link_dir"
    ln -sfn "$br_bin" "$link_dir"
    echo "  Symlinked: $link_dir -> $br_bin"

    # If prefix isn't arm-openipc-linux-musleabi-, add a compat symlink for gcc
    if [[ "$gcc_prefix" != "arm-openipc-linux-musleabi-" ]]; then
        local compat_link="$br_bin/$OPENIPC_GCC_NAME"
        if [[ ! -e "$compat_link" ]]; then
            ln -sf "$(basename "$found_gcc")" "$compat_link"
            echo "  Symlinked: $OPENIPC_GCC_NAME -> $(basename "$found_gcc")"
        fi
    fi

    write_env_sh "$link_dir"
    echo ""
    echo "  ✓ Buildroot toolchain ready."
    print_next_steps
}

# ─── Mode: --download ─────────────────────────────────────────────────────────

setup_from_download() {
    for cmd in curl tar; do
        if ! command -v "$cmd" &>/dev/null; then
            echo "Error: '$cmd' is required but not installed."
            exit 1
        fi
    done

    mkdir -p "$TOOLCHAIN_DIR"
    local tarball="$TOOLCHAIN_DIR/$MUSL_CC_ARCHIVE_NAME"
    local unpack_dir="$TOOLCHAIN_DIR/$MUSL_CC_UNPACK_DIR"

    # Check if already set up
    local final_gcc="$unpack_dir/bin/$OPENIPC_GCC_NAME"
    if [[ -x "$final_gcc" ]]; then
        echo "Toolchain already present: $final_gcc"
        echo "$("$final_gcc" --version | head -1)"
        echo ""
        echo "  If env.sh is missing, re-run to regenerate it."
        if [[ ! -f "$TOOLCHAIN_DIR/env.sh" ]]; then
            write_env_sh "$unpack_dir/bin"
        fi
        print_next_steps
        return
    fi

    # Download
    if [[ -f "$tarball" ]]; then
        echo "━━━ Archive already downloaded: $tarball"
    else
        echo "━━━ Downloading musl.cc arm-linux-musleabi toolchain (~50 MB)..."
        echo "    URL: $MUSL_CC_URL"
        if ! curl -fL --progress-bar -o "${tarball}.tmp" "$MUSL_CC_URL"; then
            rm -f "${tarball}.tmp"
            echo ""
            echo "Error: download failed."
            echo "       Check https://musl.cc/ for available toolchain archives."
            echo "       If the file was renamed, set MUSL_CC_URL in this script."
            exit 1
        fi
        mv "${tarball}.tmp" "$tarball"
        echo "  Downloaded: $tarball"
    fi

    # Extract
    echo "━━━ Extracting..."
    tar -xzf "$tarball" -C "$TOOLCHAIN_DIR"

    if [[ ! -d "$unpack_dir" ]]; then
        echo "Error: expected directory '$unpack_dir' after extraction."
        echo "       Check that the archive unpacks to '$MUSL_CC_UNPACK_DIR/'."
        exit 1
    fi

    # Add arm-openipc-linux-musleabi-gcc symlink so GNUmakefile's BIN_SUBDIR
    # produces bin/arm-openipc-linux-musleabi-gcc/, consistent with the
    # pre-built binaries already committed in that directory.
    local real_gcc="$unpack_dir/bin/${MUSL_CC_BIN_PREFIX}gcc"
    if [[ ! -x "$real_gcc" ]]; then
        echo "Error: $real_gcc not found after extraction."
        exit 1
    fi

    if [[ ! -e "$unpack_dir/bin/$OPENIPC_GCC_NAME" ]]; then
        (cd "$unpack_dir/bin" && ln -sf "${MUSL_CC_BIN_PREFIX}gcc" "$OPENIPC_GCC_NAME")
        echo "  Symlinked: $OPENIPC_GCC_NAME -> ${MUSL_CC_BIN_PREFIX}gcc"
    fi

    echo "  Version: $("$real_gcc" --version | head -1)"

    write_env_sh "$unpack_dir/bin"
    echo ""
    echo "  ✓ musl.cc toolchain ready."

    # Keep or remove the tarball
    echo ""
    read -r -p "  Remove downloaded archive to save space? [y/N] " confirm
    if [[ "${confirm,,}" == "y" ]]; then
        rm -f "$tarball"
        echo "  Removed: $tarball"
    fi

    print_next_steps
}

# ─── Entry point ─────────────────────────────────────────────────────────────

if [[ $# -eq 0 || "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
    usage
    exit 0
fi

case "${1:-}" in
    --buildroot)
        if [[ $# -lt 2 ]]; then
            echo "Error: --buildroot requires a path argument."
            usage
            exit 1
        fi
        setup_from_buildroot "$2"
        ;;
    --download)
        setup_from_download
        ;;
    --list)
        list_toolchains
        ;;
    *)
        echo "Error: unknown option '$1'"
        usage
        exit 1
        ;;
esac
